import type { TranslationUsage } from './types.ts';

/**
 * A static map of key → the places that key is used. Build this however you
 * like — hand-authored, or generated by a build-time scan of your source.
 */
export type UsageRegistry = Record<string, TranslationUsage[]>;

/**
 * Supplies usages for a key on the server. Can be backed by a {@link UsageRegistry}
 * or computed dynamically. Returning `[]` (or omitting the key) is fine.
 */
export type UsageProvider = (key: string) => TranslationUsage[] | Promise<TranslationUsage[]>;

function usageDedupeKey(usage: TranslationUsage): string {
  return [usage.id, usage.route ?? '', usage.label, usage.subItem ?? ''].join('::');
}

/**
 * Merge several usage lists into one, de-duplicating by
 * `id + route + label + subItem`. When duplicates collide, a usage marked
 * `exact: true` (observed live in the DOM) wins over a static one, and later
 * lists win over earlier ones.
 */
export function mergeUsages(
  ...lists: Array<readonly TranslationUsage[] | undefined>
): TranslationUsage[] {
  const byKey = new Map<string, TranslationUsage>();
  for (const list of lists) {
    for (const usage of list ?? []) {
      const key = usageDedupeKey(usage);
      const existing = byKey.get(key);
      if (!existing || usage.exact || !existing.exact) {
        byKey.set(key, { ...existing, ...usage });
      }
    }
  }
  return [...byKey.values()];
}

/** Build a {@link UsageProvider} from a static {@link UsageRegistry}. */
export function registryUsageProvider(registry: UsageRegistry): UsageProvider {
  return (key) => registry[key] ?? [];
}
